services:
  backend:
    image: timiliris/nocturne-backend:latest
    environment:
      DATABASE_PROVIDER: ${DATABASE_PROVIDER}
      DATABASE_URL: ${DATABASE_URL}
      GLOBAL_USERNAME: ${GLOBAL_USERNAME}
      GLOBAL_PASSWORD: ${GLOBAL_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: timiliris/nocturne-frontend:latest
    environment:
      API_URL: ${API_URL}
    ports:
      - "4200:8100"
    depends_on:
      - backend

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spotifydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
